### ISSUE TITLE
where i can find the train.json

### ISSUE THREAD

**Issue by ctxya1207** [THUDM/ImageReward#103]
Traceback (most recent call last):
  File "E:\Project\ImageReward-main\train\src\make_dataset.py", line 12, in <module>
    train_dataset = rank_pair_dataset("train")
  File "E:\Project\ImageReward-main\train\src\rank_pair_dataset.py", line 57, in __init__
    with open(self.dataset_path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'dataset\\train.json'

**Comment by xujz18** [comment]
You can download the data at [this url](https://huggingface.co/datasets/THUDM/ImageRewardDB) and process it into the desired format.
