### ISSUE TITLE
Error loading script in SD Webui 5ab7f213

### ISSUE THREAD

**Issue by gitboomer** [THUDM/ImageReward#16]
Running the most recent version of SD Webui. `pip install image-reward` ran successfully. Dropped `image_reward.py` into `C:\Users\user\stable-diffusion-webui\scripts`. SD Webui is printing the following error:
```
Error loading script: image_reward.py
Traceback (most recent call last):
  File "C:\Users\user\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\user\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\user\stable-diffusion-webui\scripts\image_reward.py", line 18, in <module>
    import ImageReward as reward
ModuleNotFoundError: No module named 'ImageReward'
```
commandline args: --xformers --autolaunch --deepdanbooru
python: 3.10.6
commit: [5ab7f213](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/5ab7f213bec2f816f9c5644becb32eb72c8ffb89)

**Comment by tongyx361** [comment]
Thank you so much for the issue! Let's resolve it together 😀

`ModuleNotFoundError: No module named 'ImageReward'` indicates that the Python interpreter failed to search for the `ImageReward` package from your Python environment.

So you might need to try checking your Python environment, which might has the following problems:
- The environment shown is different from the one actually used (this sometimes happens in Conda), try reactivating the environment with `conda activate <env_name_with_image-reward_installed>` in Conda for example.
- `pip` did not install `image-reward` successfully, try `pip show image-reward` to check if it has been installed successfully.

If the problem is still not solved after checking the above problems and trying the corresponding solutions, please feel free to continue to ask.

**Comment by bparlan** [comment]
Since my error is similar and I can provide further information, I am commenting and populating similar error. `pip install image-reward` ran successfully:

```
C:\WINDOWS\system32>pip show image-reward
Name: image-reward
Version: 1.2
Summary: ImageReward
Home-page: https://github.com/THUDM/ImageReward
Author: Jiazheng Xu, et al.
Author-email: <xjz22@mails.tsinghua.edu.cn>
License: Apache 2.0 license
Location: c:\python310\lib\site-packages
Requires: fairscale, huggingface-hub, timm, transformers
Required-by:
```

Dropped `image_reward.py` into `D:\Projects\StableRegina\stable-diffusion-webui\scripts`.
SD Webui is printing the following error:

```
Launching Web UI with arguments: --autolaunch --medvram --xformers
Error loading script: image_reward.py
Traceback (most recent call last):
  File "D:\Projects\StableRegina\stable-diffusion-webui\modules\scripts.py", line 257, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\Projects\StableRegina\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Projects\StableRegina\stable-diffusion-webui\scripts\image_reward.py", line 18, in <module>
    import ImageReward as reward
ModuleNotFoundError: No module named 'ImageReward'
```

commandline args: --medvram --xformers  
python: Python 3.10.6

**Comment by tongyx361** [comment]
> Since my error is similar and I can provide further information, I am commenting and populating similar error. `pip install image-reward` ran successfully:
> 
> ```
> C:\WINDOWS\system32>pip show image-reward
> Name: image-reward
> Version: 1.2
> Summary: ImageReward
> Home-page: https://github.com/THUDM/ImageReward
> Author: Jiazheng Xu, et al.
> Author-email: <xjz22@mails.tsinghua.edu.cn>
> License: Apache 2.0 license
> Location: c:\python310\lib\site-packages
> Requires: fairscale, huggingface-hub, timm, transformers
> Required-by:
> ```
> 
> Dropped `image_reward.py` into `D:\Projects\StableRegina\stable-diffusion-webui\scripts`. SD Webui is printing the following error:
> 
> ```
> Launching Web UI with arguments: --autolaunch --medvram --xformers
> Error loading script: image_reward.py
> Traceback (most recent call last):
>   File "D:\Projects\StableRegina\stable-diffusion-webui\modules\scripts.py", line 257, in load_scripts
>     script_module = script_loading.load_module(scriptfile.path)
>   File "D:\Projects\StableRegina\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "D:\Projects\StableRegina\stable-diffusion-webui\scripts\image_reward.py", line 18, in <module>
>     import ImageReward as reward
> ModuleNotFoundError: No module named 'ImageReward'
> ```
> 
> commandline args: --medvram --xformers python: Python 3.10.6

Thank you very much for offerring the error information!

It seems that you have encountered the same error as mentioned in [this issue](https://github.com/THUDM/ImageReward/issues/18#issuecomment-1556195075). You can refer to the suggested solution in it **(**activate venv and reinstall "image-reward"**)**.

Afterwards, that issue encountered some other errors that I couldn't reproduce. If you are able to reproduce similar errors, please let us know. Your feedback will greatly help us in improving this project!

**Comment by bparlan** [comment]
> It seems that you have encountered the same error as mentioned in [this issue](https://github.com/THUDM/ImageReward/issues/18#issuecomment-1556195075). You can refer to the suggested solution in it **(activate venv and reinstall "image-reward")**.

You were definitely right about it. Activate `venv` and reinstall `image-reward` solved my issue out. I will keep updating whenever I encounter any issue! Thanks for awesome community.
