### ISSUE TITLE
issue installing and running on sdwebui

### ISSUE THREAD

**Issue by MarkusLawson-Ho** [THUDM/ImageReward#25]
apologies if not the place but am needing help have been trying to get this to work but im struggling to figure out what step im missing, have done everything as instructed but have come at this road block, when running the install is recognized as done improperly and attempts a new one everything is checked off and it says succesfully installed but then when it trys to load the image_reward.py script it gets an error with the traceback it shows lines followed by a ModuleNotFoundError: No module named 'datasets' will paste below as the trace back, if someone can recoginse the issue and has a solution wherther is something ive missed or something please let me know asap it all looks very intruiging

"image-reward" package is successfully installed!
Error loading script: image_reward.py
Traceback (most recent call last):
  File "E:\Aishit\stable-diffusion\stable-diffusion-webui\scripts\image_reward.py", line 21, in <module>
    import ImageReward as reward
  File "E:\Aishit\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\ImageReward\__init__.py", line 3, in <module>
    from .ReFL import *
  File "E:\Aishit\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\ImageReward\ReFL.py", line 27, in <module>
    from datasets import load_dataset
ModuleNotFoundError: No module named 'datasets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Aishit\stable-diffusion\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "E:\Aishit\stable-diffusion\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\Aishit\stable-diffusion\stable-diffusion-webui\scripts\image_reward.py", line 26, in <module>
    import ImageReward as reward
  File "E:\Aishit\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\ImageReward\__init__.py", line 3, in <module>
    from .ReFL import *
  File "E:\Aishit\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\ImageReward\ReFL.py", line 27, in <module>
    from datasets import load_dataset
ModuleNotFoundError: No module named 'datasets'

Image Browser: ImageReward is not installed, cannot be used.

**Comment by tongyx361** [comment]
This error should be caused by not installing the "datasets" package.

This is odd, because "image-reward>=1.3" is set to automatically check for and install the "datasets" package when running `pip install image-reward`.

Anyway, you can try **installing the packages manually in your Python environment** by running `pip install datasets`. Note here **SD Web UI's approach to managing the Python environment**
- If you launch with `python launch.py`, Web UI will use the Python environment **you have open**.
- If you launch with a script such as `webui-user.bat`, Web UI creates a new **venv environment** in its directory. Generally, you  need some other operations to activate this environment: in the `stable-diffusion-webui\venv` directory: on Windows, for example, in the `stable-diffusion-webui\venv\Scripts` directory, run `activate` or `activate.bat` (if you are using **cmd**) or `activate.ps1` (if you are using **PowerShell**) from . If you see **the prompt `(venv)` appear at the far left of the command line**, you have successfully activated venv created by the SD Web UI.

**Comment by MarkusLawson-Ho** [comment]
think it had something to do with my install cause i decided to do a new install with the one for nividia gpus and ive maganged to get it all running with no issues whatsoever so could have been something wrong with my previous install thx for how quick you were with this though
