### ISSUE TITLE
Errors loading image_reward.py with SD-WEBUI

### ISSUE THREAD

**Issue by Spunkymanker** [THUDM/ImageReward#56]
I followed the instructions for imagereward installation, and integration into sd-webui.  Using automatic1111, getting the following when trying to startup.  Imagereward of course, does not work.  

[ImageRewarderror.txt](https://github.com/THUDM/ImageReward/files/12572090/ImageRewarderror.txt)

**Comment by tongyx361** [comment]
Thank you so much for the issue! Let's resolve it together 😀

Based on
```
importlib.metadata.PackageNotFoundError: No package metadata was found for pyarrow  
```  
The immediate cause should be that **the program did not find the `pyarrow` package metadata**.

But strangely enough, according to
```  
Requirement already satisfied: pyarrow>=8.0.0 in c:\users\comma\appdata\local\programs\python\python310\lib\site-packages (from datasets= =2.11.0->image-reward) (12.0.1)  
```  
You should already have the `pyarrow` package installed.

Anyway, I think you can try **uninstalling and reinstalling the `pyarrow` package** first.

**Comment by Spunkymanker** [comment]
After uninstalling and reinstalling pyarrow, I'm still getting the same error as far as I can tell.  Is it a path error possibly? 

pip show pyarrow

Name: pyarrow
Version: 13.0.0
Summary: Python library for Apache Arrow
Home-page: https://arrow.apache.org/
Author:
Author-email:
License: Apache License, Version 2.0
Location: c:\users\comma\appdata\local\programs\python\python310\lib\site-packages
Requires: numpy
Required-by: datasets

My %path% is: 
'C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Program Files (x86)\Razer\ChromaBroadcast\bin;C:\Program Files\Razer\ChromaBroadcast\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\Program Files\PuTTY\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;;C:\Program Files\Docker\Docker\resources\bin;C:\Users\comma\AppData\Local\Programs\Python\Python310\Scripts\;C:\Users\comma\AppData\Local\Programs\Python\Python310\;C:\Users\comma\AppData\Local\Microsoft\WindowsApps;C:\Users\comma\.dotnet\tools;C:\Users\comma\AppData\Local\Microsoft\WinGet\Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\ffmpeg-6.0-full_build\bin'

[ImageRewarderror2.txt](https://github.com/THUDM/ImageReward/files/12580794/ImageRewarderror2.txt)

**Comment by tongyx361** [comment]
> After uninstalling and reinstalling pyarrow, I'm still getting the same error as far as I can tell. Is it a path error possibly?
> 
> pip show pyarrow
> 
> Name: pyarrow Version: 13.0.0 Summary: Python library for Apache Arrow Home-page: https://arrow.apache.org/ Author: Author-email: License: Apache License, Version 2.0 Location: c:\users\comma\appdata\local\programs\python\python310\lib\site-packages Requires: numpy Required-by: datasets
> 
> My %path% is: 'C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Program Files (x86)\Razer\ChromaBroadcast\bin;C:\Program Files\Razer\ChromaBroadcast\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\Program Files\PuTTY;C:\Program Files\dotnet;C:\Program Files\Git\cmd;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\ProgramData\chocolatey\bin;;C:\Program Files\Docker\Docker\resources\bin;C:\Users\comma\AppData\Local\Programs\Python\Python310\Scripts;C:\Users\comma\AppData\Local\Programs\Python\Python310;C:\Users\comma\AppData\Local\Microsoft\WindowsApps;C:\Users\comma.dotnet\tools;C:\Users\comma\AppData\Local\Microsoft\WinGet\Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\ffmpeg-6.0-full_build\bin'
> 
> [ImageRewarderror2.txt](https://github.com/THUDM/ImageReward/files/12580794/ImageRewarderror2.txt)

That's so confusing. Could you please provide a minimal reproduction procedure from scratch?

**Comment by Spunkymanker** [comment]
The attached text file 'imagerewarderror2.txt' is a single load sequence of the webui that contains the errors loading image reward as follows: 
```
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 13 (delta 5), reused 12 (delta 5), pack-reused 0
Unpacking objects: 100% (13/13), 10.91 KiB | 558.00 KiB/s, done.
From https://github.com/AUTOMATIC1111/stable-diffusion-webui
 * [new branch]        make-InputAccordion-work-with-ui-config -> origin/make-InputAccordion-work-with-ui-config
 + af4a03b7...e785402b thread-safe-extranetworks-list_items -> origin/thread-safe-extranetworks-list_items  (forced update)
Already up to date.
venv "E:\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
[Auto-Photoshop-SD] Attempting auto-update...
[Auto-Photoshop-SD] switch branch to extension branch.
checkout_result: Your branch is up to date with 'origin/master'.

[Auto-Photoshop-SD] Current Branch.
branch_result: * master

[Auto-Photoshop-SD] Fetch upstream.
fetch_result:
[Auto-Photoshop-SD] Pull upstream.
pull_result: Already up to date.
Launching Web UI with arguments: --listen --medvram --opt-sdp-attention
No module 'xformers'. Proceeding without it.
"image-reward" package has not been properly installed. Installing...
Requirement already satisfied: image-reward in c:\users\comma\appdata\local\programs\python\python310\lib\site-packages (1.3)
Requirement already satisfied: timm==0.6.13 in c:\users\comma\appdata\local\programs\python\python310\lib\site-packages (from image-reward) (0.6.13)
Requirement already satisfied: transformers==4.27.4 in c:\users\comma\appdata\local\programs\python\python310\lib\site-packages (from image-reward) (4.27.4)
Requirement already satisfied: fairscale==0.4.13 in c:\users\comma\appdata\local\programs\python\python310\lib\site-packages (from image-reward) (0.4.13)
Requirement already satisfied: huggingface-hub==0.13.4 in c:\users\comma\appdata\local\programs\python\python310\lib\site-packages (from image-reward) (0.13.4)
Requirement already satisfied: diffusers==0.16.0 in c:\users\comma\appdata\local\programs\python\python310\lib\site-packages (from image-reward) (0.16.0)
Requirement already satisfied: accelerate==0.16.0 in c:\users\comma\appdata\local\programs\python\python310\lib\site-packages (from image-reward) (0.16.0)
Requirement already satisfied: datasets==2.11.0 in c:\users\comma\appdata\local\programs\python\python310\lib\site-packages (from image-reward) (2.11.0)
Requirement already satisfied: numpy>=1.17 in c:\users\comma\appdata\local\programs\python\python310\lib\site-packages (from accelerate==0.16.0->image-reward) (1.23.4)
Requirement already satisfied: packaging>=20.0 in c:\users\comma\appdata\local\programs\python\python310\lib\site-packages (from accelerate==0.16.0->image-reward) (20.9)
Requirement already satisfied: psutil in c:\users\comma\appdata\roaming\python\python310\site-packages (from accelerate==0.16.0->image-reward) (5.9.1)
Requirement already satisfied: pyyaml in c:\users\comma\appdata\local\programs\python\python310\lib\site-packages (from accelerate==0.16.0->image-reward) (5.4.1)
Requirement already satisfied: torch>=1.4.0 in c:\users\comma\appdata\local\programs\python\python310\lib\site-packages (from accelerate==0.16.0->image-reward) (2.0.0+cu118)
Requirement already satisfied: pyarrow>=8.0.0 in c:\users\comma\appdata\local\programs\python\python310\lib\site-packages (from datasets==2.11.0->image-reward) (13.0.0)
Requirement already satisfied: dill<0.3.7,>=0.3.0 in c:\users\comma\appdata\local\programs\python\python310\lib\site-packages (from datasets==2.11.0->image-reward) (0.3.6)
Requirement already satisfied: pandas in c:\users\comma\appdata\local\programs\python\python310\lib\site-packages (from datasets==2.11.0->image-reward) (2.0.1)
Requirement already satisfied: requests>=2.19.0 in c:\users\comma\appdata\roaming\python\python310\site-packages (from datasets==2.11.0->image-reward) (2.27.1)
Requirement already satisfied: tqdm>=4.62.1 in c:\users\comma\appdata\roaming\python\python310\site-packages (from datasets==2.11.0->image-reward) (4.64.0)
Requirement already satisfied: xxhash in c:\users\comma\appdata\local\programs\python\python310\lib\site-packages (from datasets==2.11.0->image-reward) (3.2.0)
Requirement already satisfied: multiprocess in c:\users\comma\appdata\local\programs\python\python310\lib\site-packages (from datasets==2.11.0->image-reward) (0.70.14)
Requirement already satisfied: fsspec[http]>=2021.11.1 in c:\users\comma\appdata\local\programs\python\python310\lib\site-packages (from datasets==2.11.0->image-reward) (2023.6.0)
Requirement already satisfied: aiohttp in c:\users\comma\appdata\roaming\python\python310\site-packages (from datasets==2.11.0->image-reward) (3.8.1)
Requirement already satisfied: responses<0.19 in c:\users\comma\appdata\local\programs\python\python310\lib\site-packages (from datasets==2.11.0->image-reward) (0.18.0)
Requirement already satisfied: Pillow in c:\users\comma\appdata\local\programs\python\python310\lib\site-packages (from diffusers==0.16.0->image-reward) (9.5.0)
Requirement already satisfied: filelock in c:\users\comma\appdata\local\programs\python\python310\lib\site-packages (from diffusers==0.16.0->image-reward) (3.7.1)
Requirement already satisfied: importlib-metadata in c:\users\comma\appdata\local\programs\python\python310\lib\site-packages (from diffusers==0.16.0->image-reward) (6.8.0)
Requirement already satisfied: regex!=2019.12.17 in c:\users\comma\appdata\local\programs\python\python310\lib\site-packages (from diffusers==0.16.0->image-reward) (2023.6.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\comma\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub==0.13.4->image-reward) (4.7.1)
Requirement already satisfied: torchvision in c:\users\comma\appdata\local\programs\python\python310\lib\site-packages (from timm==0.6.13->image-reward) (0.15.1+cu118)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in c:\users\comma\appdata\local\programs\python\python310\lib\site-packages (from transformers==4.27.4->image-reward) (0.13.3)
Requirement already satisfied: attrs>=17.3.0 in c:\users\comma\appdata\local\programs\python\python310\lib\site-packages (from aiohttp->datasets==2.11.0->image-reward) (23.1.0)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in c:\users\comma\appdata\roaming\python\python310\site-packages (from aiohttp->datasets==2.11.0->image-reward) (2.0.12)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\comma\appdata\roaming\python\python310\site-packages (from aiohttp->datasets==2.11.0->image-reward) (6.0.2)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\comma\appdata\roaming\python\python310\site-packages (from aiohttp->datasets==2.11.0->image-reward) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\comma\appdata\roaming\python\python310\site-packages (from aiohttp->datasets==2.11.0->image-reward) (1.7.2)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\comma\appdata\roaming\python\python310\site-packages (from aiohttp->datasets==2.11.0->image-reward) (1.3.0)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\comma\appdata\roaming\python\python310\site-packages (from aiohttp->datasets==2.11.0->image-reward) (1.2.0)
Requirement already satisfied: pyparsing>=2.0.2 in c:\users\comma\appdata\local\programs\python\python310\lib\site-packages (from packaging>=20.0->accelerate==0.16.0->image-reward) (3.0.9)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\comma\appdata\roaming\python\python310\site-packages (from requests>=2.19.0->datasets==2.11.0->image-reward) (1.26.9)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\comma\appdata\roaming\python\python310\site-packages (from requests>=2.19.0->datasets==2.11.0->image-reward) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in c:\users\comma\appdata\roaming\python\python310\site-packages (from requests>=2.19.0->datasets==2.11.0->image-reward) (3.3)
Requirement already satisfied: sympy in c:\users\comma\appdata\local\programs\python\python310\lib\site-packages (from torch>=1.4.0->accelerate==0.16.0->image-reward) (1.12)
Requirement already satisfied: networkx in c:\users\comma\appdata\local\programs\python\python310\lib\site-packages (from torch>=1.4.0->accelerate==0.16.0->image-reward) (3.1)
Requirement already satisfied: jinja2 in c:\users\comma\appdata\local\programs\python\python310\lib\site-packages (from torch>=1.4.0->accelerate==0.16.0->image-reward) (3.1.2)
Requirement already satisfied: colorama in c:\users\comma\appdata\roaming\python\python310\site-packages (from tqdm>=4.62.1->datasets==2.11.0->image-reward) (0.4.4)
Requirement already satisfied: zipp>=0.5 in c:\users\comma\appdata\local\programs\python\python310\lib\site-packages (from importlib-metadata->diffusers==0.16.0->image-reward) (3.8.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\comma\appdata\roaming\python\python310\site-packages (from pandas->datasets==2.11.0->image-reward) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\comma\appdata\local\programs\python\python310\lib\site-packages (from pandas->datasets==2.11.0->image-reward) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in c:\users\comma\appdata\local\programs\python\python310\lib\site-packages (from pandas->datasets==2.11.0->image-reward) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\comma\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.8.2->pandas->datasets==2.11.0->image-reward) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\comma\appdata\roaming\python\python310\site-packages (from jinja2->torch>=1.4.0->accelerate==0.16.0->image-reward) (2.1.1)
Requirement already satisfied: mpmath>=0.19 in c:\users\comma\appdata\local\programs\python\python310\lib\site-packages (from sympy->torch>=1.4.0->accelerate==0.16.0->image-reward) (1.3.0)
"image-reward" package is successfully installed!
*** Error loading script: image_reward.py
    Traceback (most recent call last):
      File "E:\stable-diffusion-webui\scripts\image_reward.py", line 21, in <module>
        import ImageReward as reward
      File "E:\stable-diffusion-webui\venv\lib\site-packages\ImageReward\__init__.py", line 3, in <module>
        from .ReFL import *
      File "E:\stable-diffusion-webui\venv\lib\site-packages\ImageReward\ReFL.py", line 27, in <module>
        from datasets import load_dataset
      File "E:\stable-diffusion-webui\venv\lib\site-packages\datasets\__init__.py", line 43, in <module>
        from .arrow_dataset import Dataset
      File "E:\stable-diffusion-webui\venv\lib\site-packages\datasets\arrow_dataset.py", line 64, in <module>
        from . import config
      File "E:\stable-diffusion-webui\venv\lib\site-packages\datasets\config.py", line 43, in <module>
        PYARROW_VERSION = version.parse(importlib_metadata.version("pyarrow"))
      File "C:\Users\comma\AppData\Local\Programs\Python\Python310\lib\importlib\metadata\__init__.py", line 996, in version
        return distribution(distribution_name).version
      File "C:\Users\comma\AppData\Local\Programs\Python\Python310\lib\importlib\metadata\__init__.py", line 969, in distribution
        return Distribution.from_name(distribution_name)
      File "C:\Users\comma\AppData\Local\Programs\Python\Python310\lib\importlib\metadata\__init__.py", line 548, in from_name
        raise PackageNotFoundError(name)
    importlib.metadata.PackageNotFoundError: No package metadata was found for pyarrow

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "E:\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\stable-diffusion-webui\scripts\image_reward.py", line 26, in <module>
        import ImageReward as reward
      File "E:\stable-diffusion-webui\venv\lib\site-packages\ImageReward\__init__.py", line 3, in <module>
        from .ReFL import *
      File "E:\stable-diffusion-webui\venv\lib\site-packages\ImageReward\ReFL.py", line 27, in <module>
        from datasets import load_dataset
      File "E:\stable-diffusion-webui\venv\lib\site-packages\datasets\__init__.py", line 43, in <module>
        from .arrow_dataset import Dataset
      File "E:\stable-diffusion-webui\venv\lib\site-packages\datasets\arrow_dataset.py", line 64, in <module>
        from . import config
      File "E:\stable-diffusion-webui\venv\lib\site-packages\datasets\config.py", line 43, in <module>
        PYARROW_VERSION = version.parse(importlib_metadata.version("pyarrow"))
      File "C:\Users\comma\AppData\Local\Programs\Python\Python310\lib\importlib\metadata\__init__.py", line 996, in version
        return distribution(distribution_name).version
      File "C:\Users\comma\AppData\Local\Programs\Python\Python310\lib\importlib\metadata\__init__.py", line 969, in distribution
        return Distribution.from_name(distribution_name)
      File "C:\Users\comma\AppData\Local\Programs\Python\Python310\lib\importlib\metadata\__init__.py", line 548, in from_name
        raise PackageNotFoundError(name)
    importlib.metadata.PackageNotFoundError: No package metadata was found for pyarrow

---
python_server_full_path:  E:\stable-diffusion-webui\extensions\Auto-Photoshop-StableDiffusion-Plugin\server/python_server
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: E:\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
Civitai Helper: No setting file, use default
2023-09-11 10:22:44,470 - ControlNet - INFO - ControlNet v1.1.409
ControlNet preprocessor location: E:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-09-11 10:22:44,692 - ControlNet - INFO - ControlNet v1.1.409
Installing pywin32
Loading weights [524882ba22] from E:\stable-diffusion-webui\models\Stable-diffusion\fantasyWorld_v10.safetensors
Creating model from config: E:\stable-diffusion-webui\configs\v1-inference.yaml
load Sadtalker Checkpoints from E:\stable-diffusion-webui\extensions\SadTalker\checkpoints\
Applying attention optimization: sdp... done.
[VRAMEstimator] Loaded benchmark data.
Running on local URL:  http://0.0.0.0:7860
Model loaded in 7.4s (load weights from disk: 0.3s, create model: 0.7s, apply weights to model: 1.1s, load textual inversion embeddings: 2.2s, calculate empty prompt: 3.0s).

To create a public link, set `share=True` in `launch()`.
COMMANDLINE_ARGS does not contain --api, API won't be mounted.
Startup time: 58.1s (prepare environment: 18.0s, import torch: 5.5s, import gradio: 2.8s, setup paths: 2.4s, initialize shared: 0.2s, other imports: 2.1s, setup codeformer: 0.2s, list SD models: 3.8s, load scripts: 12.3s, create ui: 6.6s, gradio launch: 4.3s).
```
pip show pyarrow results:
```
Name: pyarrow
Version: 13.0.0
Summary: Python library for Apache Arrow
Home-page: https://arrow.apache.org/
Author:
Author-email:
License: Apache License, Version 2.0
Location: c:\users\comma\appdata\local\programs\python\python310\lib\site-packages
Requires: numpy
Required-by: datasets
```

My path/venv
```
My %path% is:
'C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler
C:\Program Files (x86)\Razer Chroma SDK\bin
C:\Program Files\Razer Chroma SDK\bin
C:\Program Files (x86)\Razer\ChromaBroadcast\bin
C:\Program Files\Razer\ChromaBroadcast\bin 
C:\Windows\system32
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0
C:\Windows\System32\OpenSSH
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps
C:\Program Files\PuTTY
C:\Program Files\dotnet
C:\Program Files\Git\cmd
C:\WINDOWS\system32
C:\WINDOWS;C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0
C:\WINDOWS\System32\OpenSSH
C:\ProgramData\chocolatey\bin
C:\Program Files\Docker\Docker\resources\bin
C:\Users\comma\AppData\Local\Programs\Python\Python310\Scripts
C:\Users\comma\AppData\Local\Programs\Python\Python310
C:\Users\comma\AppData\Local\Microsoft\WindowsApps
C:\Users\comma.dotnet\tools
C:\Users\comma\AppData\Local\Microsoft\WinGet\Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\ffmpeg-6.0-full_build\bin'
```

**Comment by Spunkymanker** [comment]
Activating the separate venv and reinstalling imagereward fixed the problem!   Thank you!  I didn't realize I  was using two separate python environments.  

Now I just need to learn how to use it!

**Comment by tongyx361** [comment]
> Activating the separate venv and reinstalling imagereward fixed the problem! Thank you! I didn't realize I was using two separate python environments.
> 
> Now I just need to learn how to use it!

That's great! The Python environment management in SD Web UI is such a quirk XD
I'll close this issue and wish you an enjoyable experience with our work~
